package gameproject;

import java.util.ArrayList;

public class ArrayListPlayer1{

  public static void main (String[] args){
    ArrayList<Player4> member = new ArrayList<>();
    member.add(new Player4("Kirana",2889000,450));
    member.add(new Player4("Dido",8900000,460));
    member.add(new Player4("Benu",2500000,255));
    member.add(new Player4("Olip",4900000,440));
    member.add(new Player4("Nyuk",3300000,320));
  
  }

}
